-- 💗 PINK WORLD GUESTBOOK
-- Paste this into Supabase SQL Editor and run it.

create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 30),
  message text not null check (char_length(message) between 1 and 180),
  created_at timestamptz not null default now()
);

alter table public.guestbook enable row level security;

revoke all on table public.guestbook from anon, authenticated;
grant select on table public.guestbook to anon, authenticated;
grant insert on table public.guestbook to authenticated;

create policy "everyone can read guestbook"
on public.guestbook for select
to anon, authenticated
using (true);

create policy "logged in users can write"
on public.guestbook for insert
to authenticated
with check ((select auth.uid()) = user_id);
